### PR TITLE
Upgrade lemmy pipeline to spaCy v3

### PR DESCRIPTION
**Pull request by thomashacker**
Adjusted architecture by adding the `@Language.factory()` registry 🎉

### CODE REVIEW

**Comment by joakimwar** [comment]
This looks like what I need. I am trying to use lemmy together with [swedish spacy](https://github.com/Kungbib/swedish-spacy), since lemmy needs to POS tags to do lemmatization well. After loading the nlp pipeline from swedish spacy I simply do 
```python
nlp.add_pipe('lemmy', 'lemmy')
```
Is this the correct way to use the changes you've made here? Also, if you happen to have any other hints on how to effectively do Swedish lemmatization I would highly appreciate it 😄 I have tried spacy_udpipe, and spacy_stanza, but neither of them work well for my needs, so swedish_spacy + lemmy is my current attempt to make it work.

**Comment by thomashacker** [comment]
With this PR you should be able to get `lemmy` working by:
```
    import spacy
    import lemmy.pipe

    nlp = spacy.load("da_core_news_sm")
    nlp.add_pipe("lemmy")
```
In terms of lemmatization hints, we just published a blog post of our new experimental [edit-tree-lemmatizer](https://explosion.ai/blog/edit-tree-lemmatizer) 🤗 A machine learning-based lemmatizer that learns rules from data that makes it easier to create lemmatization for almost every language!

**Comment by joakimwar** [comment]
Thanks! Edit-tree lemmatization looks really interesting. When it comes to Swedish data I can only find the treebanks from universal dependencies, which means ~7.4k sentences and their lemmatized versions. Do I understand correctly that this is the type of training data I need? If so I might look into training one for Swedish.

**Comment by thomashacker** [comment]
Yes, exactly! It'd be interesting to see your results on the Swedish dataset. If you want, you can share your results on the [spaCy discussion forum](https://github.com/explosion/spaCy/discussions) 😄

**Comment by gaardhus** [comment]
I'm running a library [graph-tool](https://graph-tool.skewed.de/) through a docker container with arc-linux and am getting an error with spacy it seems.

I tried installing your version through 
`pip install git+https://github.com/thomashacker/lemmy.git`

and then run your example:
```
import spacy
print(spacy.__version__)

import lemmy.pipe

nlp = spacy.load("da_core_news_sm")

nlp.add_pipe("lemmy")
```
Output:
```
3.2.0

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-abbe648ba30c> in <module>
      2 print(spacy.__version__)
      3 
----> 4 import lemmy.pipe
      5 
      6 nlp = spacy.load("da_core_news_sm")

/usr/lib/python3.9/site-packages/lemmy/pipe/__init__.py in <module>
      1 """Initialization code for Lemmy pipeline."""
----> 2 from lemmy.pipe.component import load

/usr/lib/python3.9/site-packages/lemmy/pipe/component.py in <module>
      1 # coding: utf-8
      2 """A spaCy pipeline component."""
----> 3 from spacy.symbols import PRON_LEMMA
      4 from spacy.tokens import Token
      5 

ImportError: cannot import name 'PRON_LEMMA' from 'spacy.symbols' (/usr/lib/python3.9/site-packages/spacy/symbols.cpython-39-x86_64-linux-gnu.so)
```

Maybe it has something to do with the docker container I'm running it in ?

**Comment by thomashacker** [comment]
Closing `PR` since the repo seems to be abandoned

**Pull request closed without merging**
